name: Mirror Repo to Friend

on:
  push:
    branches:
      - '**'  # ✅ Trigger for all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # Important — prevents overwriting PAT

      - name: Mirror push to Friend Repo
        env:
          FRIEND_REPO_TOKEN: ${{ secrets.FRIEND_REPO_TOKEN1 }}
        run: |
          echo "➡️ Pushing branch: $GITHUB_REF_NAME"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Add friend repo using PAT
          git remote add friend https://x-access-token:${FRIEND_REPO_TOKEN}@github.com/Yashkhandelwal683/Frontend-Dev.git

          # Show remotes (for debug)
          git remote -v

          # Push same branch to friend repo
          git push friend $GITHUB_REF_NAME:$GITHUB_REF_NAME --force
