name: Mirror Repo to Friend

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Yash Khandelwal"
          git config --global user.email "YashKhandelwal683@gmail.com"
          git config --system --unset credential.helper || true
          git config --global --unset credential.helper || true

      - name: Add friend remote
        env:
          FRIEND_REPO_TOKEN1: ${{ secrets.FRIEND_REPO_TOKEN1 }}
        run: |
          echo "Pushing branch: $GITHUB_REF_NAME"
          git remote add friend "https://YashKhandelwal683:${FRIEND_REPO_TOKEN1}@github.com/Yashkhandelwal683/Frontend-Dev.git"
          git remote -v

      - name: Push to friend repo (excluding workflows)
        env:
          FRIEND_REPO_TOKEN1: ${{ secrets.FRIEND_REPO_TOKEN1 }}
        run: |
          git fetch origin $GITHUB_REF_NAME
          git checkout $GITHUB_REF_NAME

          if [ -d ".github/workflows" ]; then
            echo "Removing workflow files before push..."
            git rm -r --cached .github/workflows || true
            rm -rf .github/workflows
          else
            echo "No workflows directory found — skipping removal."
          fi

          git diff --cached --quiet || git commit -m "Exclude workflows from sync"

          echo "Pushing to friend's repo..."
          git push "https://YashKhandelwal683:${FRIEND_REPO_TOKEN1}@github.com/Yashkhandelwal683/Frontend-Dev.git" HEAD:$GITHUB_REF_NAME --force
