name: Mirror Repo to Friend

on:
  push:
    branches:
      - '**'   # Run for all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch (no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # 🔴 Prevents GitHub bot token override

      - name: Configure Git
        run: |
          git config --global user.name "Yash Khandelwal"
          git config --global user.email "YashKhandelwal683@gmail.com"
          git config --system --unset credential.helper || true
          git config --global --unset credential.helper || true

      - name: Push to Yash Repo (excluding workflows)
        env:
          FRIEND_REPO_TOKEN: ${{ secrets.FRIEND_REPO_TOKEN1 }}
        run: |
          echo "Pushing branch: $GITHUB_REF_NAME"

          # Add your target repo as remote using the PAT
          git remote add friend "https://YashKhandelwal683:${FRIEND_REPO_TOKEN}@github.com/Yashkhandelwal683/Frontend-Dev.git"
          git remote -v

          # Exclude workflow files if they exist
          if [ -d ".github/workflows" ]; then
            echo "Removing workflows before push..."
            git rm -r --cached .github/workflows || true
            rm -rf .github/workflows
            git diff --cached --quiet || git commit -m "Exclude workflows from sync"
          fi

          # Push to friend's repo (create branch if not exists)
          git push friend HEAD:$GITHUB_REF_NAME --force
