name: Mirror Repo to Friend

on:
  push:
    branches:
      - '**'   # Trigger on all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Yash Khandelwal"
          git config --global user.email "YashKhandelwal683@gmail.com"

      - name: Add friend remote
        run: |
          echo "Pushing branch: $GITHUB_REF_NAME"
          git remote add friend https://x-access-token:${{ secrets.FRIEND_REPO_TOKEN1 }}@github.com/Yashkhandelwal683/Frontend-Dev.git
          git remote -v

      - name: Push to friend repo (excluding workflows)
        run: |
          # Make sure the branch exists locally
          git fetch origin $GITHUB_REF_NAME
          git checkout $GITHUB_REF_NAME

          # Remove .github/workflows from staging so they aren’t pushed
          rm -rf .github/workflows/
          git add -A
          git reset .github/workflows/

          # Push to friend’s repo (create branch if not exists)
          git push friend HEAD:$GITHUB_REF_NAME --force
