name: Mirror Repo to Friend

on:
  push:
    branches:
      - '**'   # Trigger on all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Yash Khandelwal"
          git config --global user.email "YashKhandelwal683@gmail.com"

      - name: Add friend remote
        run: |
          echo "Pushing branch: $GITHUB_REF_NAME"
          git remote add friend https://x-access-token:${{ secrets.FRIEND_REPO_TOKEN1 }}@github.com/Yashkhandelwal683/Frontend-Dev.git
          git remote -v

      - name: Push to friend repo (excluding workflows)
        run: |
          # Ensure we’re on the correct branch
          git fetch origin $GITHUB_REF_NAME
          git checkout $GITHUB_REF_NAME

          # Exclude .github/workflows if it exists
          if [ -d ".github/workflows" ]; then
            echo "Removing workflow files before push..."
            git rm -r --cached .github/workflows || true
            rm -rf .github/workflows
          else
            echo "No workflows directory found — skipping removal."
          fi

          # Commit removal if any change occurred
          git diff --cached --quiet || git commit -m "Exclude workflows from sync"

          # Push to friend repo (create branch if missing)
          git push friend HEAD:$GITHUB_REF_NAME --force
